### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Sonic0** [Mortafix/Saturno#1]
Hi @Mortafix ,
Thank you very much for this tool, very very simple and useful! 😎

It missing a dependency in the requirements.txt file: _youtube_dl_

In fact, I have got this error during the first execution time:
```python
$ saturno manage

Traceback (most recent call last):
  File "/home/User/.virtualenvs/saturno/bin/saturno", line 5, in <module>
    from saturno.saturno import main
  File "/home/User/.virtualenvs/saturno/lib/python3.8/site-packages/saturno/saturno.py", line 13, in <module>
    from youtube_dl import YoutubeDL
ModuleNotFoundError: No module named 'youtube_dl'
```

**Comment by Mortafix** [comment]
Thanks @Sonic0,
I really appreciate you like this simple project!

I update the requirements in `1.7.4`, thanks for the issue.
